#! /bin/bash

#list of node tests
declare testarr=(
	[1]=sleepTheSystemWithNoKeyWhenItIsRequired
	[2]=sleepTheSystemWithKeyWhenItIsRequired
	[3]=discoverServerUnderTest
	[4]=launchApplicationNotRecognized
	[5]=launchApplicationInRunningStateWithNoPayload
	[6]=launchApplicationInRunningStateWithPayload
	[7]=launchApplicationInStoppedStateWithPayload
	[8]=launchApplicationInStoppedStateWithNoPayload
	[9]=launchApplicationInHiddenStateWithNoPayload
	[10]=launchApplicationInHiddenStateWithPayload
	[11]=launchApplicationWithExcessPayload
	[12]=stopInvalidApplicationInstance
	[13]=stopApplicationInRunningState
	[14]=stopApplicationInStoppedState
	[15]=stopApplicationInHiddenState
	[16]=hideInvalidApplicationInstance
	[17]=hideApplicationInHiddenState
	[18]=hideApplicationInRunningState
	[19]=stateChangesWithoutDIAL
	[20]=launchHideStopStressTest
	[21]=checkStatusofSystemApp
)		

#display all individual tests in array
function list_tests(){
	count=1;		
	for i in "${testarr[@]}"
	do
		echo "$count: $i" 
		count=$((count+1));
	done;
}

#run all YT DIAL 2.2 tests with debug log 
function run_all(){
	node ~/bin/"Test Package"/dial-reference-2020/server/tests/js_tests/tests/yt_cert_tests.js --host $host --app $1 --loglevel debug;
}

#running individual tests from test array
function run_individ(){
	echo Enter Device IP address and Press Enter;
	read host;
	echo Enter Test number from list:
	echo "-----------------------------------"
	list_tests;
	echo ""
	echo "Enter q to quit"
	echo "-----------------------------------"

	read input;	
	while [ $input != 'q' ];
	do
		testcase=${testarr[input]};
		node ~/bin/"Test Package"/dial-reference-2020/server/tests/js_tests/tests/$testcase.js --host $host --app $1 --loglevel debug;
		echo Enter Test number from list:
		echo "-----------------------------------"
		list_tests;
		echo ""
		echo "Enter q to quit"
		echo "-----------------------------------"
		read input;	
	done;	
}

echo ' _________________________________________________'; 
echo '|						 |';
echo '|		Enter Test option:	 	 |';
echo '|						 |';
echo '|	1) Pacemaker				 |';
echo '|	2) Websockets				 |';
echo '|	3) Node.js compliance(depreciated) 	 |';
echo '| 	4) YT Node.js compliance(2020)        	 |';
echo '| 	5) YTTV Node.js compliance(2020)         |';
echo '| 	4) YTKids Node.js compliance(2020)       |';
echo '|					  	 |';
echo '|	x) Exit				         |';
echo '|________________________________________________|';

read option

case $option in
	1)
	pacelink=$(ipconfig getifaddr en0);
	echo $pacelink:4433 | pbcopy;
	sleep 1;
	echo Press -Enter- to open mirror. Paste in URL field;
	read enter;
	open "https://qual-e.appspot.com/mirror";
	python ~/bin/"Test Package"/pacemaker.py;
	;;
	2)
	weblink=$(ipconfig getifaddr en0);
	echo qual-e.appspot.com/localtransport/index.html?turl=http://$weblink:5050 | pbcopy;
	sleep 1;	
	echo Press -Enter- to open mirror and paste to URL field;
	read enter;
	open "https://qual-e.appspot.com/mirror";
	node ~/bin/"Test Package"/lt_test_runner/lt_test_runner.js;
	;;
	3)
	echo  '______________________________'
	echo '|                             |' 
	echo '|  a) Run All                 |' 
	echo '|  b) Individual              |' 
	echo  '______________________________'
	read select
	case $select in
		#run all node.js
		a)
		echo Enter Device IP address and Press Enter;
		read host;
		node ~/bin/"Test Package"/dial-reference-2019/server/tests/js_tests/tests/tests.js --host $host --app YouTube --loglevel debug;
		;;
		#Individual loop
		b)
		run_individ;
	;;
	esac;;
	4)
	echo  '______________________________'
	echo '|                             |' 
	echo '|  a) Run All                 |' 
	echo '|  b) Individual              |' 
	echo  '______________________________'
	read select
	case $select in
		#run all node.js
		a)
		echo Enter Device IP address and Press Enter;
		read host;
		run_all YouTube
		;;
		#Individual loop
		b)
		run_individ YouTube;	
	;;
	esac;;
	5)
	echo  '______________________________'
	echo '|                             |' 
	echo '|  a) Run All                 |' 
	echo '|  b) Individual              |' 
	echo  '______________________________'
	read select
	case $select in
		#run all node.js
		a)
		echo Enter Device IP address and Press Enter;
		read host;
		run_all YouTubeTV
		;;
		#Individual loop
		b)
		run_individ YouTubeTV;	
	;;
	esac;;
	6)
	echo  '______________________________'
	echo '|                             |' 
	echo '|  a) Run All                 |' 
	echo '|  b) Individual              |' 
	echo  '______________________________'
	read select
	case $select in
		#run all node.js
		a)
		echo Enter Device IP address and Press Enter;
		read host;
		run_all YouTubeKids;
		;;
		#Individual loop
		b)
		run_individ YouTubeKids;	
	;;
	esac;;
	x|X)
	echo Bye!
	;;
	*)
	echo Enter correct selection!;
	echo \'x\' to Exit;
	read option;
	continue;
	;;
esac;

exit 155;
